### ISSUE TITLE
Add billable/non-billable toggle

### ISSUE THREAD

**Issue by PFython** [PFython/time_is_money#6]
A common requirement is to log time to activities but with no intention of charging for them.  This could be pro bono charity work, training/research/education, pre-sales effort etc. that someone wants to track even though it earns no money for them (directly).

**Comment by FelixTheC** [comment]
do you want to have this as an additional flag in the command line? 

like
```
tim.py START client task CHARITY
```

**Comment by PFython** [comment]
That's a good idea Felix... Strictly speaking charities aren't the only case where we might want non-billable work though, so maybe we could use the keyword "NONBILLABLE" or "PROBONO" instead?

**Comment by FelixTheC** [comment]
`tim.py START client task PROBONO` I will also add a column in the csv called PROBONO to stay consitent with 0=False, 1=True?? And PROBONO will be optional therefore PROBONO in the csv will mostly be 0.

**Comment by PFython** [comment]
Sounds good Felix!  Apologies again for distant/slow responses due to other client project...

**Comment by FelixTheC** [comment]
you don't need to apologize as this is something we do in our free time I also have not everyday time.
